version: "3"
services:
  ssh-dev0:
    image: ssh-dev:latest
    hostname: debian_ssh-dev0
    networks:
      ssh-dev:
        ipv4_address: 172.26.0.10
  ssh-dev1:
    image: ssh-dev:latest
    hostname: debian_ssh-dev1
    networks:
      ssh-dev:
        ipv4_address: 172.26.0.11
  ssh-dev2:
    image: ssh-dev:latest
    hostname: debian_ssh-dev2
    networks:
      ssh-dev:
        ipv4_address: 172.26.0.12
networks:
  ssh-dev:
    driver: bridge
    ipam:
     config:
       - subnet: 172.26.0.0/16
